defaults: &defaults
  working_directory: ~/javascript-express
  docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: v12-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: v12-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test_with_ava:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v12-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install TAP and cross-env
          command: |
                   mkdir -p ~/javascript-express/reports
                   sudo npm install -g npm@5
                   sudo npm install tap-xunit -g
                   npm install cross-env
      - run:
          name: test
          command: npm test | tap-xunit > ~/javascript-express/reports/reports.xml
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: ~/javascript-express/reports/test_results.xml
          prefix: tests
      - store_artifacts:
          path: ~/javascript-express/reports/coverage
          prefix: coverage
      - store_test_results:
          path: ~/javascript-express/reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_with_ava
