defaults: &defaults
  working_directory: ~/javascript-express
  docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@5
      - run:
          name: mkdir
          command: mkdir -p ~/javascript-express/workspace
      - restore_cache:
          key: v13-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install 
      - persist_to_workspace:
          root: workspace
          paths:
            - client
      - save_cache:
          key: v13-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test_with_ava:
    <<: *defaults
    parallelism: 2    
    steps:
      - checkout
      - restore_cache:
          key: v13-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install TAP and cross-env
          command: |
                   mkdir -p ~/javascript-express/reports
                   mkdir -p ~/javascript-express/reports/ava
                   mkdir -p ~/javascript-express/artifacts
                   sudo npm install -g npm@5
                   sudo npm install tap-xunit -g
                   npm install cross-env
      - run:
          name: test
          command: npm test | tap-xunit > ~/javascript-express/reports/ava/reports.xml
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: ~/javascript-express/artifacts/test_results.xml
          prefix: tests
      - store_artifacts:
          path: ~/javascript-express/artifacts/coverage
          prefix: coverage
      - store_test_results:
          path: ~/javascript-express/reports
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - dev
    jobs:
      - build
      - test_with_ava
  build_and_test:
     jobs:
       - build
       - test_with_ava
