defaults: &defaults
  working_directory: ~/circleci-demo-javascript-express
  docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: v6-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: v6-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test_with_ava:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install TAP and cross-env
          command: |
                   sudo npm install -g npm@5
                   sudo npm install tap-xunit -g
                   npm install cross-env
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - run:
          name: XMLify results
          command: cat results.tap | tap-xunit > test-results.xml
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_with_ava
